apiVersion: apps/v1
kind: Deployment
metadata:
  name: gomart-backend
  labels:
    app: gomart-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gomart-backend
  template:
    metadata:
      labels:
        app: gomart-backend
    spec:
      containers:
      - name: gomart-backend
        image: mosimaiain/gomart:main
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: gomart-config
        - secretRef:
            name: gomart-secrets
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5