apiVersion: apps/v1
kind: Deployment
metadata:
  name: gomart-backend
  labels:
    app: gomart-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gomart-backend
  template:
    metadata:
      labels:
        app: gomart-backend
    spec:
      containers:
      - name: gomart-backend
        image: mosimaiain/gomart:main
        ports:
        - containerPort: 8080
        env:
        - name: DB_SOURCE
          value: "postgresql://root:supersecret@postgres-service:5432/gomart_db?sslmode=disable"
        - name: HTTP_SERVER_ADDRESS
          value: ":8080"
        - name: AWS_REGION
          value: "ap-northeast-1"
        - name: COGNITO_CLIENT_ID
          value: "your-cognito-client-id"
        - name: COGNITO_CLIENT_SECRET
          value: "your-cognito-client-secret"
        - name: COGNITO_REDIRECT_URI
          value: "http://localhost:8080/cognito/callback"
        - name: COGNITO_DOMAIN
          value: "your-cognito-domain.auth.ap-northeast-1.amazoncognito.com"
        - name: COGNITO_USER_POOL_ID
          value: "ap-northeast-1_YourPoolId"
        - name: atApiKeys
          value: "your-africastalking-api-key"
        - name: atUsername
          value: "sandbox"
        - name: atShortCode
          value: "15548"
        - name: atSandbox
          value: "true"
        - name: EMAIL_HOST
          value: "smtp.gmail.com"
        - name: EMAIL_PORT
          value: "587"
        - name: EMAIL_USERNAME
          value: "your-email@gmail.com"
        - name: EMAIL_PASSWORD
          value: "your-app-password"
        - name: EMAIL_FROM
          value: "your-email@gmail.com"