// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	CategoryID   uuid.UUID          `json:"category_id"`
	CategoryName string             `json:"category_name"`
	ParentID     pgtype.UUID        `json:"parent_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	IsDeleted    pgtype.Bool        `json:"is_deleted"`
}

type Order struct {
	OrderID     uuid.UUID          `json:"order_id"`
	CustomerID  uuid.UUID          `json:"customer_id"`
	OrderNumber string             `json:"order_number"`
	Status      pgtype.Text        `json:"status"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	IsDeleted   pgtype.Bool        `json:"is_deleted"`
}

type OrderItem struct {
	OrderItemID uuid.UUID          `json:"order_item_id"`
	OrderID     uuid.UUID          `json:"order_id"`
	ProductID   uuid.UUID          `json:"product_id"`
	Quantity    int32              `json:"quantity"`
	UnitPrice   pgtype.Numeric     `json:"unit_price"`
	TotalPrice  pgtype.Numeric     `json:"total_price"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	IsDeleted   pgtype.Bool        `json:"is_deleted"`
}

type Product struct {
	ProductID     uuid.UUID          `json:"product_id"`
	ProductName   string             `json:"product_name"`
	Description   pgtype.Text        `json:"description"`
	Price         pgtype.Numeric     `json:"price"`
	Sku           string             `json:"sku"`
	StockQuantity int32              `json:"stock_quantity"`
	CategoryID    uuid.UUID          `json:"category_id"`
	IsActive      pgtype.Bool        `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	IsDeleted     pgtype.Bool        `json:"is_deleted"`
}
