// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountActiveProducts(ctx context.Context) (int64, error)
	CountCustomers(ctx context.Context) (int64, error)
	CountOrderItems(ctx context.Context) (int64, error)
	CountOrderItemsByOrder(ctx context.Context, orderID uuid.UUID) (int64, error)
	CountOrders(ctx context.Context) (int64, error)
	CountOrdersByStatus(ctx context.Context, status NullOrderStatus) (int64, error)
	CountProducts(ctx context.Context) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	GetCategory(ctx context.Context, categoryID uuid.UUID) (Category, error)
	GetCategoryAverageProductPrice(ctx context.Context, categoryID uuid.UUID) (pgtype.Numeric, error)
	GetCategoryChildren(ctx context.Context, parentID pgtype.UUID) ([]Category, error)
	GetCustomer(ctx context.Context, customerID uuid.UUID) (Customer, error)
	GetCustomerByEmail(ctx context.Context, email string) (Customer, error)
	GetCustomerByOpenIDSub(ctx context.Context, openidSub string) (Customer, error)
	GetOrder(ctx context.Context, orderID uuid.UUID) (Order, error)
	GetOrderByNumber(ctx context.Context, orderNumber string) (Order, error)
	GetOrderItem(ctx context.Context, orderItemID uuid.UUID) (OrderItem, error)
	GetOrderItemsWithDetails(ctx context.Context, orderID uuid.UUID) ([]GetOrderItemsWithDetailsRow, error)
	GetOrderTotalFromItems(ctx context.Context, orderID uuid.UUID) (interface{}, error)
	GetProduct(ctx context.Context, productID uuid.UUID) (Product, error)
	GetProductBySKU(ctx context.Context, sku string) (Product, error)
	GetRootCategories(ctx context.Context) ([]Category, error)
	ListActiveProducts(ctx context.Context) ([]Product, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListCustomers(ctx context.Context) ([]Customer, error)
	ListCustomersBySetupStatus(ctx context.Context, setupCompleted pgtype.Bool) ([]Customer, error)
	ListOrderItems(ctx context.Context) ([]OrderItem, error)
	ListOrderItemsByOrder(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	ListOrderItemsByProduct(ctx context.Context, productID uuid.UUID) ([]OrderItem, error)
	ListOrders(ctx context.Context) ([]Order, error)
	ListOrdersByCustomer(ctx context.Context, customerID uuid.UUID) ([]Order, error)
	ListOrdersByDateRange(ctx context.Context, arg ListOrdersByDateRangeParams) ([]Order, error)
	ListOrdersByStatus(ctx context.Context, status NullOrderStatus) ([]Order, error)
	ListProducts(ctx context.Context) ([]Product, error)
	ListProductsByCategory(ctx context.Context, categoryID uuid.UUID) ([]Product, error)
	ListProductsInStock(ctx context.Context) ([]Product, error)
	SoftDeleteCategory(ctx context.Context, categoryID uuid.UUID) error
	SoftDeleteCustomer(ctx context.Context, customerID uuid.UUID) error
	SoftDeleteOrder(ctx context.Context, orderID uuid.UUID) error
	SoftDeleteOrderItem(ctx context.Context, orderItemID uuid.UUID) error
	SoftDeleteOrderItemsByOrder(ctx context.Context, orderID uuid.UUID) error
	SoftDeleteProduct(ctx context.Context, productID uuid.UUID) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateCustomerSetupStatus(ctx context.Context, arg UpdateCustomerSetupStatusParams) (Customer, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
	UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) (OrderItem, error)
	UpdateOrderItemQuantity(ctx context.Context, arg UpdateOrderItemQuantityParams) (OrderItem, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateOrderTotal(ctx context.Context, arg UpdateOrderTotalParams) (Order, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductStatus(ctx context.Context, arg UpdateProductStatusParams) (Product, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
